from django.urls import path
from . import views

urlpatterns = [
    path('home', views.home, name = 'home'),
    path('all_books', views.all_books, name = 'all_books'),
    path('genre/<str:slug>', views.category_detail, name = 'category_detail'),
    path('pdf/<str:slug>', views.book_detail, name = 'book_detail'),
    path('searched_books', views.search_book, name = 'book_search'),
    path('register', views.register_page, name = 'register'),
    path('login', views.login_page, name = 'login'),
    path('logout', views.logout_user, name = 'logout'),
    path('scrape', views.scrape_book, name = 'scrape_book'),
    path('upload', views.importCSV, name = 'importCSV'),
    path('form', views.bookform, name='form'),
    path('dashboard', views.adminpage, name='adminpage'),
    path('bookadmin', views.bookadmin, name='bookadmin'),
    path('bookadmin/delete/<int:pk>/', views.bookadmin_delete, name='bookadmin-delete'),
    path('bookadmin/update/<int:pk>/', views.bookadmin_update, name='bookadmin-update'),
    path('useradmin', views.useradmin, name='useradmin'),
    path('useradmin/delete/<int:pk>/', views.useradmin_delete, name='useradmin-delete'),
    path('lowtohigh', views.lowtohigh, name='lowtohigh'),
    path('hightolow', views.hightolow, name='hightolow'),
    path('priceless', views.priceless, name='priceless'),
    path('pricey', views.pricey, name='pricey'),
    path('newest', views.newest, name='newest'),
    path('oldest', views.oldest, name='oldest'),
    path('english', views.english, name='english'),
    path('indonesian', views.indonesian, name='indonesian'),
    path('other', views.other, name='other'),
    path('art', views.art, name='art'),
    path('education', views.education, name='education'),
    path('family', views.family, name='family'),
    path('fiction', views.fiction, name='fiction'),
    path('food', views.food, name='food'),
    path('horror', views.horror, name='horror'),
    path('kesehatan', views.kesehatan, name='kesehatan'),
    path('komputer', views.komputer, name='komputer'),
    path('komik', views.komik, name='komik'),
    path('sejarah', views.sejarah, name='sejarah'),
]