# Generated by Django 2.2 on 2022-01-11 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0003_auto_20220111_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='compatible',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, default=None, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='halaman',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='book',
            name='harga',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.CharField(default=None, max_length=3),
        ),
        migrations.AlterField(
            model_name='book',
            name='ratingsum',
            field=models.CharField(default=None, max_length=3),
        ),
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.TextField(default=None),
        ),
    ]
