# Generated by Django 2.2 on 2022-01-11 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0005_auto_20220111_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='compatible',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='halaman',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='book',
            name='harga',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='book',
            name='ratingsum',
            field=models.CharField(max_length=3),
        ),
    ]
