# Generated by Django 2.2 on 2022-01-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0007_auto_20220111_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rilis',
            field=models.DateTimeField(null=True),
        ),
    ]
