# Generated by Django 2.2 on 2022-01-13 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0011_mymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyScrape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=200)),
            ],
        ),
    ]
