# Generated by Django 2.2 on 2022-01-13 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0012_myscrape'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myscrape',
            name='link',
            field=models.URLField(),
        ),
    ]
