# Generated by Django 2.2 on 2022-01-14 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0013_auto_20220113_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.DeleteModel(
            name='MyScrape',
        ),
    ]
