# Generated by Django 2.2 on 2022-01-17 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0015_csv'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='category',
            field=models.ManyToManyField(related_name='books', to='bookapp.Category'),
        ),
    ]
