# Generated by Django 2.2 on 2022-01-17 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0016_todo_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='category',
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(related_name='books', to='bookapp.Category'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='todo',
            name='category',
            field=models.ManyToManyField(related_name='_todo_category_+', to='bookapp.Category'),
        ),
    ]
